# 菜单配置（若不需要某项可直接删除）
menu:
  - text: 首页
    link: /
    icon: home
    class: menu-home
  - text: 归档
    link: /archives
    icon: archive
    class: menu-archive
  - text: 分类
    link: javascript:;
    category: true
    icon: bookmark
    class: menu-category
  - text: 读书
    link: /reading
    icon: book
    class: menu-reading
  - text: 关于
    link: /about
    icon: user
    class: menu-about

# 颜色配置
color:
    header: indigo
    footer: indigo
    page_nav: indigo
    side_nav: indigo darken-1
    tag: green accent-4
    link: indigo
    pagination: green
    tab: green
    archive_item: indigo
    fab: green
    fab_2: blue
    fab_3: orange
    new: pink
    about_header: indigo
    about_title: indigo

excerpt_link: Read More
archive_yearly: true

# 版权信息
copyright: © 2016 jkissday.online, All rights reserved.

# Disqus评论shortname，若为空则不启用
disqus_shortname:
# 多说shortname，若为空则不启用
duoshuo_shortname: jkissday

# Google分析track id，若为空则不启用
google_analytics:
# 腾讯分析sId，若为空则不启用
tencent_analytics:

# 高亮的主题，若为空则使用默认主题
google_code_prettify: prettify-tomorrow-night-eighties

# 是否启用MathJax数学公式渲染。如果你确认整个站点的博文都不会用到Latex数学公式，可以将其该项设为false提高页面加载速度
mathjax: true

# 是否开启打赏
donate_message: 看完啦? 够意思!  土豪~交个朋友吧...